// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import type {PrismaConfig} from "prisma";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
}) satisfies PrismaConfig;
