export const navigationElementsNameCodes = [
    "NAVBAR",
    "SIDEBAR",
    "FOOTER",
] as const;

export type NavigationElementNameCode = (typeof navigationElementsNameCodes)[number];

type NavigationSectionCode<N extends NavigationElementNameCode> = `${N}_SECTION_${string}`;

export const sidebarSectionCodes = {
    SIDEBAR_SECTION_FEATURES: "SIDEBAR_SECTION_FEATURES",
    SIDEBAR_SECTION_ABOUT: "SIDEBAR_SECTION_ABOUT",
    SIDEBAR_SECTION_MY_DECKS: "SIDEBAR_SECTION_MY_DECKS",
} satisfies Record<NavigationSectionCode<"SIDEBAR">, NavigationSectionCode<"SIDEBAR">>;

export const footerSectionCodes = {
    FOOTER_SECTION_FEATURES: "FOOTER_SECTION_FEATURES",
} satisfies Record<NavigationSectionCode<"FOOTER">, NavigationSectionCode<"FOOTER">>;

type NavigationItemCode<N extends NavigationElementNameCode> = `${N}_ITEM_${string}`;

export const navbarItemCodes = {
    NAVBAR_ITEM_FEATURE_SPACED_REPETITION: "NAVBAR_ITEM_FEATURE_SPACED_REPETITION",
    NAVBAR_ITEM_FEATURE_AI_ASSISTANCE: "NAVBAR_ITEM_FEATURE_AI_ASSISTANCE",
    NAVBAR_ITEM_FEATURE_TRUSTWORTHY_ANSWERS: "NAVBAR_ITEM_FEATURE_TRUSTWORTHY_ANSWERS",
    NAVBAR_ITEM_DECKS: "NAVBAR_ITEM_DECKS",
    NAVBAR_ITEM_SHARED_DECKS: "NAVBAR_ITEM_SHARED_DECKS",
    NAVBAR_ITEM_EDUCATIONAL_RESOURCES: "NAVBAR_ITEM_EDUCATIONAL_RESOURCES",
} satisfies Record<NavigationItemCode<"NAVBAR">, NavigationItemCode<"NAVBAR">>;

export const sidebarItemCodes = {
    SIDEBAR_ITEM_FEATURE_SPACED_REPETITION: "SIDEBAR_ITEM_FEATURE_SPACED_REPETITION",
    SIDEBAR_ITEM_FEATURE_AI_ASSISTANCE: "SIDEBAR_ITEM_FEATURE_AI_ASSISTANCE",
    SIDEBAR_ITEM_FEATURE_TRUSTWORTHY_ANSWERS: "SIDEBAR_ITEM_FEATURE_TRUSTWORTHY_ANSWERS",
    SIDEBAR_ITEM_FEATURE_STATISTICS: "SIDEBAR_ITEM_FEATURE_STATISTICS",
    SIDEBAR_ITEM_ABOUT: "SIDEBAR_ITEM_ABOUT",
} satisfies Record<NavigationItemCode<"SIDEBAR">, NavigationItemCode<"SIDEBAR">>;

export const footerItemCodes = {
    FOOTER_ITEM_FEATURE_SPACED_REPETITION: "FOOTER_ITEM_FEATURE_SPACED_REPETITION",
    FOOTER_ITEM_FEATURE_AI_ASSISTANCE: "FOOTER_ITEM_FEATURE_AI_ASSISTANCE",
    FOOTER_ITEM_FEATURE_TRUSTWORTHY_ANSWERS: "FOOTER_ITEM_FEATURE_TRUSTWORTHY_ANSWERS",
    FOOTER_ITEM_FEATURE_STATISTICS: "FOOTER_ITEM_FEATURE_STATISTICS",
} satisfies Record<NavigationItemCode<"FOOTER">, NavigationItemCode<"FOOTER">>