export const userPanelCodes = {
    USER_PANEL_SETTINGS: "USER_PANEL_SETTINGS",
    USER_PANEL_CHANGE_THEME: "USER_PANEL_CHANGE_THEME",
    USER_PANEL_CHANGE_LANGUAGE: "USER_PANEL_CHANGE_LANGUAGE",
    USER_PANEL_LOGOUT: "USER_PANEL_LOGOUT",
} as const satisfies Record<`USER_PANEL_${string}`, `USER_PANEL_${string}`>;