import type {Publication} from "@/types/Publication";

export const publicationsMock: Publication[] = [
    {
        id: 1,
        name: "Japanese Core 2k",
        description: "High-frequency Japanese vocabulary for beginners.",
        coverImagePath: "/covers/jp-core-2k.jpg",
        rating: 4.7,
    },
    {
        id: 2,
        name: "English Phrasal Verbs",
        description: "Common phrasal verbs with contextual examples.",
        coverImagePath: "/covers/en-phrasal-verbs.jpg",
        rating: 4.4,
    },
    {
        id: 3,
        name: "Spanish A1 Vocabulary",
        description: "Essential Spanish words for absolute beginners.",
        coverImagePath: "/covers/es-a1.jpg",
        rating: 4.2,
    },
    {
        id: 4,
        name: "German Articles Mastery",
        description: "Practice der, die, das with structured repetition.",
        coverImagePath: "/covers/de-articles.jpg",
        rating: 4.5,
    },
    {
        id: 5,
        name: "French Verb Conjugations",
        description: "Present and past tense conjugation patterns.",
        coverImagePath: "/covers/fr-verbs.jpg",
        rating: 4.3,
    },
    {
        id: 6,
        name: "Korean Hangul Basics",
        description: "Learn to read and write Hangul efficiently.",
        coverImagePath: "/covers/kr-hangul.jpg",
        rating: 4.8,
    },
    {
        id: 7,
        name: "Latin Medical Terminology",
        description: "Foundational medical and anatomical terms.",
        coverImagePath: "/covers/latin-med.jpg",
        rating: 4.1,
    },
    {
        id: 8,
        name: "World Capitals",
        description: "Countries and their capitals worldwide.",
        coverImagePath: "/covers/capitals.jpg",
        rating: 4.0,
    },
    {
        id: 9,
        name: "SAT Vocabulary",
        description: "High-yield vocabulary for standardized tests.",
        coverImagePath: "/covers/sat-vocab.jpg",
        rating: 4.6,
    },
    {
        id: 10,
        name: "Physics Formulas",
        description: "Core physics equations with brief explanations.",
        coverImagePath: "/covers/physics.jpg",
        rating: 4.3,
    },
    {
        id: 11,
        name: "Organic Chemistry Reactions",
        description: "Key reaction mechanisms and reagents.",
        coverImagePath: "/covers/org-chem.jpg",
        rating: 4.5,
    },
    {
        id: 12,
        name: "Linux Command Line",
        description: "Essential Linux commands for daily use.",
        coverImagePath: "/covers/linux-cli.jpg",
        rating: 4.7,
    },
    {
        id: 13,
        name: "Data Structures Basics",
        description: "Arrays, lists, stacks, queues, and trees.",
        coverImagePath: "/covers/data-structures.jpg",
        rating: 4.6,
    },
    {
        id: 14,
        name: "Art History Timeline",
        description: "Major art movements and representative works.",
        coverImagePath: "/covers/art-history.jpg",
        rating: 3.9,
    },
    {
        id: 15,
        name: "Music Theory Fundamentals",
        description: "Intervals, scales, chords, and harmony.",
        coverImagePath: "/covers/music-theory.jpg",
        rating: 4.4,
    },
    {
        id: 16,
        name: "US Constitutional Amendments",
        description: "All amendments with concise explanations.",
        coverImagePath: "/covers/us-constitution.jpg",
        rating: 4.1,
    },
    {
        id: 17,
        name: "Human Anatomy",
        description: "Major systems and anatomical terminology.",
        coverImagePath: "/covers/anatomy.jpg",
        rating: 4.5,
    },
    {
        id: 18,
        name: "Statistics Essentials Statistics Essentials Statistics Essentials",
        description: "Probability, distributions, and hypothesis testing.",
        coverImagePath: "/covers/statistics.jpg",
        rating: 4.2,
    },
    {
        id: 19,
        name: "Business English",
        description: "Professional English for meetings and emails.",
        coverImagePath: "/covers/business-en.jpg",
        rating: 4.3,
    },
    {
        id: 20,
        name: "Philosophy: Key Concepts",
        description: "Core ideas from major philosophical traditions.",
        coverImagePath: "/covers/philosophy.jpg",
        rating: 4.0,
    }
];