import type {ResourceNameCode} from "./resource-name-codes.config";

type ResourcePropertyCode<R extends ResourceNameCode> = `${R}_${string}`;

export const userPropertyCodes = {
    USER_RESOURCE_NAME: "USER_RESOURCE_NAME",
    USER_USERNAME: "USER_USERNAME",
    USER_EMAIL: "USER_EMAIL",
    USER_PASSWORD: "USER_PASSWORD",
} satisfies Record<ResourcePropertyCode<"USER">, ResourcePropertyCode<"USER">>;

export const flashcardPropertyCodes = {
    FLASHCARD_RESOURCE_NAME: "FLASHCARD_RESOURCE_NAME",
    FLASHCARD_FRONT: "FLASHCARD_FRONT",
    FLASHCARD_BACK: "FLASHCARD_BACK",
    FLASHCARD_INTERVAL_DAYS: "FLASHCARD_INTERVAL_DAYS",
    FLASHCARD_DUE_AT: "FLASHCARD_DUE_AT",
    FLASHCARD_DEFAULT_DUE_AT: "FLASHCARD_DEFAULT_DUE_AT",
    /* ===== AI GENERATED CODE START ===== */
    FLASHCARD_REVIEW_COMPLETE_TITLE: "FLASHCARD_REVIEW_COMPLETE_TITLE",
    FLASHCARD_REVIEW_COMPLETE_MESSAGE: "FLASHCARD_REVIEW_COMPLETE_MESSAGE",
    FLASHCARD_REVIEW_COMPLETE_BACK_TO_DECK: "FLASHCARD_REVIEW_COMPLETE_BACK_TO_DECK",
    FLASHCARD_REVIEW_COMPLETE_CONGRATS: "FLASHCARD_REVIEW_COMPLETE_CONGRATS",
    /* ===== AI GENERATED CODE END ===== */
} satisfies Record<ResourcePropertyCode<"FLASHCARD">, ResourcePropertyCode<"FLASHCARD">>;

export const deckPropertyCodes = {
    DECK_RESOURCE_NAME: "DECK_RESOURCE_NAME",
    DECK_NAME: "DECK_NAME",
    DECK_DESCRIPTION: "DECK_DESCRIPTION",
    DECK_IS_PUBLIC: "DECK_IS_PUBLIC",
    DECK_PUBLIC: "DECK_PUBLIC",
    DECK_PRIVATE: "DECK_PRIVATE",
    DECK_COVER: "DECK_COVER",
    DECK_FLASHCARDS_COUNT: "DECK_FLASHCARDS_COUNT",
    DECK_INFO: "DECK_INFO",
    DECK_FLASHCARDS: "DECK_FLASHCARDS",
    DECK_EDUCATIONAL_RESOURCES: "DECK_EDUCATIONAL_RESOURCES",
    /* ===== AI GENERATED CODE START ===== */
    DECK_SEARCH_PLACEHOLDER: "DECK_SEARCH_PLACEHOLDER",
    DECK_PAGE_DESCRIPTION: "DECK_PAGE_DESCRIPTION",
    /* ===== AI GENERATED CODE END ===== */
} satisfies Record<ResourcePropertyCode<"DECK">, ResourcePropertyCode<"DECK">>;

export const educationalResourcePropertyCodes = {
    EDUCATIONAL_RESOURCE_RESOURCE_NAME: "EDUCATIONAL_RESOURCE_RESOURCE_NAME",
    EDUCATIONAL_RESOURCE_NAME: "EDUCATIONAL_RESOURCE_NAME",
    EDUCATIONAL_RESOURCE_DESCRIPTION: "EDUCATIONAL_RESOURCE_DESCRIPTION",
    EDUCATIONAL_RESOURCE_FILE: "EDUCATIONAL_RESOURCE_FILE",
    EDUCATIONAL_RESOURCE_COVER: "EDUCATIONAL_RESOURCE_COVER",
    /* ===== AI GENERATED CODE START ===== */
    EDUCATIONAL_RESOURCE_SEARCH_PLACEHOLDER: "EDUCATIONAL_RESOURCE_SEARCH_PLACEHOLDER",
    EDUCATIONAL_RESOURCE_PAGE_DESCRIPTION: "EDUCATIONAL_RESOURCE_PAGE_DESCRIPTION",
    /* ===== AI GENERATED CODE END ===== */
} satisfies Record<ResourcePropertyCode<"EDUCATIONAL_RESOURCE">, ResourcePropertyCode<"EDUCATIONAL_RESOURCE">>;

export const chatPropertyCodes = {
    CHAT_RESOURCE_NAME: "CHAT_RESOURCE_NAME",
    CHAT_TITLE: "CHAT_TITLE",
    CHAT_DEFAULT_TITLE: "CHAT_DEFAULT_TITLE",
    CHAT_NO_MESSAGES: "CHAT_NO_MESSAGES",
} satisfies Record<ResourcePropertyCode<"CHAT">, ResourcePropertyCode<"CHAT">>;

export const chatMessagePropertyCodes = {
    CHAT_MESSAGE_RESOURCE_NAME: "CHAT_MESSAGE_RESOURCE_NAME",
    CHAT_MESSAGE_CONTENT: "CHAT_MESSAGE_CONTENT",
} satisfies Record<ResourcePropertyCode<"CHAT_MESSAGE">, ResourcePropertyCode<"CHAT_MESSAGE">>;

/* ===== AI GENERATED CODE START ===== */
export const sharedDeckPropertyCodes = {
    SHARED_DECK_RESOURCE_NAME: "SHARED_DECK_RESOURCE_NAME",
    SHARED_DECK_NAME: "SHARED_DECK_NAME",
    SHARED_DECK_DESCRIPTION: "SHARED_DECK_DESCRIPTION",
    SHARED_DECK_OWNER: "SHARED_DECK_OWNER",
    SHARED_DECK_RATING: "SHARED_DECK_RATING",
    SHARED_DECK_NO_RATING: "SHARED_DECK_NO_RATING",
    SHARED_DECK_FLASHCARDS_COUNT: "SHARED_DECK_FLASHCARDS_COUNT",
    SHARED_DECK_REVIEWS: "SHARED_DECK_REVIEWS",
    SHARED_DECK_NO_REVIEWS: "SHARED_DECK_NO_REVIEWS",
    SHARED_DECK_LEAVE_REVIEW: "SHARED_DECK_LEAVE_REVIEW",
    SHARED_DECK_ADD_TO_COLLECTION: "SHARED_DECK_ADD_TO_COLLECTION",
    SHARED_DECK_ADDING: "SHARED_DECK_ADDING",
    SHARED_DECK_NO_DECKS_FOUND: "SHARED_DECK_NO_DECKS_FOUND",
    SHARED_DECK_NO_DECKS_WITH_TAGS: "SHARED_DECK_NO_DECKS_WITH_TAGS",
    SHARED_DECK_NO_DECKS_WITH_RATING: "SHARED_DECK_NO_DECKS_WITH_RATING",
    SHARED_DECK_NO_DECKS_YET: "SHARED_DECK_NO_DECKS_YET",
    SHARED_DECK_SEARCH_PLACEHOLDER: "SHARED_DECK_SEARCH_PLACEHOLDER",
    SHARED_DECK_FILTER_BY_RATING: "SHARED_DECK_FILTER_BY_RATING",
    SHARED_DECK_FILTER_BY_TAGS: "SHARED_DECK_FILTER_BY_TAGS",
    SHARED_DECK_CLEAR_FILTERS: "SHARED_DECK_CLEAR_FILTERS",
    SHARED_DECK_PAGE_TITLE: "SHARED_DECK_PAGE_TITLE",
    SHARED_DECK_PAGE_DESCRIPTION: "SHARED_DECK_PAGE_DESCRIPTION",
    SHARED_DECK_FLASHCARDS: "SHARED_DECK_FLASHCARDS",
    SHARED_DECK_NO_FLASHCARDS: "SHARED_DECK_NO_FLASHCARDS",
    SHARED_DECK_SCROLL_HINT: "SHARED_DECK_SCROLL_HINT",
    SHARED_DECK_BE_FIRST_REVIEWER: "SHARED_DECK_BE_FIRST_REVIEWER",
    SHARED_DECK_YOUR_DECK: "SHARED_DECK_YOUR_DECK",
    SHARED_DECK_RATING_LABEL: "SHARED_DECK_RATING_LABEL",
} satisfies Record<ResourcePropertyCode<"SHARED_DECK">, ResourcePropertyCode<"SHARED_DECK">>;

export const feedbackPropertyCodes = {
    FEEDBACK_RESOURCE_NAME: "FEEDBACK_RESOURCE_NAME",
    FEEDBACK_CONTENT: "FEEDBACK_CONTENT",
    FEEDBACK_RATING: "FEEDBACK_RATING",
    FEEDBACK_RATING_REQUIRED: "FEEDBACK_RATING_REQUIRED",
    FEEDBACK_CONTENT_PLACEHOLDER: "FEEDBACK_CONTENT_PLACEHOLDER",
    FEEDBACK_SUBMIT: "FEEDBACK_SUBMIT",
    FEEDBACK_RATE_OUT_OF_5: "FEEDBACK_RATE_OUT_OF_5",
} satisfies Record<ResourcePropertyCode<"FEEDBACK">, ResourcePropertyCode<"FEEDBACK">>;
/* ===== AI GENERATED CODE END ===== */